development:
  rutausr: 
  rutamodelo: 
  rutaprg: 
  prg: 
  rutaexpportprg: 
  expportprg: 
deploy:
  origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  destinomd: /Users/hwo/git/pgn/pgn-078
  origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  gitorigen: /Users/hwo/git/pgn/pgn-078
publish:
  gitorigen: /Users/hwo/git/pgn/pgn-078 
  
mddoc:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  rutaMacMD: /git/devdocs/devocs-contd/contd/docx
  rutaCompleta: no
mdpdf:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  rutaMacMD: /git/devdocs/devocs-contd/contd/pdf
  rutaCompleta: no
mdtex:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-templtex.ajs
  rutaMacMD: /git/devdocs/devocs-contd/contd/tex
  rutaCompleta: no
mdppt:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/devdocs/devocs-contd/contd/ppt
  rutaCompleta: no
mdhtml:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/devdocs/devocs-contd/contd/html
  rutaCompleta: no
