deploy:
  prgreporthtml: exportSingle-htmlCLI.ajs
  prgreportmd: exportSingle-md.ajs
  rutareport: /github/workspace/contd/report

mdextraer:
  rutamodelo: $HOME/git/model-repository/modelocontd-ae
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaMacMD: $HOME/git/devdocs/devocs-contd/contd
  rutareport: $HOME/git/devdocs/devocs-contd/contd/report
  devdocalias: 123estrategia
  rutaCompleta: no

mddocx:
  expportprg: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_test: Tx-orderview.ajs
  expportprg_rept: exportSingle-md.ajs
mdpdf:
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdtex:
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-templtex.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdppt:
  expportprg: Tx-exportToMarkdown-CLI-templppt.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-templppt.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdhtml:
  expportprg: exportSingle-htmlCLI.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs 
