development:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  prg: Tx-exportToMarkdown-CLI-templppt.ajs
  vistadoc: hvppt
  rutaexpportprg: /Users/hwo/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
deploy:
  # origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  # destinomd: /Users/hwo/gh/pgn/pgn-078
  # origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  # gitorigen: /Users/hwo/gh/pgn/pgn-078
publish:
  # gitorigen: /Users/hwo/gh/pgn/pgn-078 
  