development:
  rutausr: /Users/hwo/git
  rutamodelo: /Users/hwo/git/models/modelocontenidos
  rutaprg: /Users/hwo/git/jarchi-hwo/scr/exportToMarkdown-tmepl-CLI.ajs
  vistadoc: hv
  rutaexpportprg: /Users/hwo/gh/jarchi-hwo/scr/exportSingle-htmlCLI.ajs
deploy:
  origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  destinomd: /Users/hwo/gh/pgn/pgn-078
  origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  gitorigen: /Users/hwo/gh/pgn/pgn-078
publish:
  gitorigen: /Users/hwo/gh/pgn/pgn-078 
  