deploy:
  origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  destinomd: /Users/hwo/gh/pgn/pgn-078
  origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
  prgreporthtml: exportSingle-htmlCLI.ajs
  prgreportmd: exportSingle-md.ajs
  rutareport: /git/devdocs/devocs-contd/contd/report
ccambio:
  gitorigen: /Users/hwong23/git/devdocs/devocs-contd
publish:
  gitorigen: /Users/hwo/gh/pgn/pgn-078 

mddocx:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-md.ajs 
  expportprg_all: exportSingle-md.ajs 
  rutaMacMD: /git/devdocs/devocs-contd/contd/docx
  rutaCompleta: no
mdpdf:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_all: exportSingle-htmlCLI.ajs 
  rutaMacMD: /git/devdocs/devocs-contd/contd/pdf
  rutaCompleta: no
mdtex:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-templtex.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_all: exportSingle-htmlCLI.ajs 
  rutaMacMD: /git/devdocs/devocs-contd/contd/tex
  rutaCompleta: no
mdppt:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-templppt.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-templppt.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_all: exportSingle-htmlCLI.ajs 
  rutaMacMD: /git/devdocs/devocs-contd/contd/ppt
  rutaCompleta: no  
mdhtml:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/gh/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_all: exportSingle-htmlCLI.ajs 
  rutaMacMD: /gh/devdocs/devocs-contd/contd/html
  rutaCompleta: no
