deploy:
  # origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  # destinomd: /Users/hw/pgn/pgn-078
  # origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
  prgreporthtml: exportSingle-htmlCLI.ajs
  prgreportmd: exportSingle-md.ajs
  rutareport: /github/workspace/contd/report
ccambio:
  gitorigen: /Users/hw/devdocs/devocs-contd
# publish:
#   gitorigen: /Users/hw/pgn/pgn-078 

mddocx:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_all: exportSingle-md.ajs 
  rutaMacMD: /contd/mddocx
  rutaCompleta: no
mdpdf:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
  rutaMacMD: /contd/mdpdf
  rutaCompleta: no
mdtex:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  rutaMacMD: /contd/mdtex
  rutaCompleta: no
mdppt:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  expportprg: Tx-exportToMarkdown-CLI-templppt.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-templppt.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  rutaMacMD: /contd/mdppt
  rutaCompleta: no
mdhtml:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs 
  rutaMacMD: /contd/mdhtml
  rutaCompleta: no
