development:
  rutausr: /Users/hwong23/git
  rutamodelo: /Users/hwong23/git/archigit/modelocontenidos
  # rutaprg: /Users/hwong23/git/jarchi-hwo/scr/exportToMarkdown-templ-CLI.ajs
  # rutaprg: /Users/hwong23/git/jarchi-hwo/scr/exportToMarkdown-CLI.ajs
  rutaprg: /Users/hwong23/git/jarchi-hwo/scr/markdownDrivingViews-devdocsCLI.ajs
  vistadoc: hvdd
  rutaexpportprg: /Users/hwong23/git/jarchi-hwo/scr/exportSingle-htmlCLI.ajs
deploy:
  # origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  # destinomd: /Users/hwo/gh/pgn/pgn-078
  # origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  # gitorigen: /Users/hwo/gh/pgn/pgn-078
publish:
  # gitorigen: /Users/hwo/gh/pgn/pgn-078 
  
