deploy:
  # origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  # destinomd: /Users/hw/pgn/pgn-078
  # origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
  prgreporthtml: exportSingle-htmlCLI.ajs
  prgreportmd: exportSingle-md.ajs
  rutareport: /github/workspace/contd/report
ccambio:
  gitorigen: /Users/hw/devdocs/devocs-contd
# publish:
#   gitorigen: /Users/hw/pgn/pgn-078 

mdextraer:
  rutamodelo: /github/workspace
  rutaprg: /github/workspace/jarchi-hwo/scr
  rutaMacMD: /github/workspace/contd
  rutaDeployContd: /home/contd
  devdocalias: bmmpropuesta
  rutaCompleta: no

mddocx:
  expportprg: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  expportprg_test: Tx-orderview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-md.ajs
mdpdf:
  expportprg: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdtex:
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-md.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdppt:
  expportprg: Tx-exportToMarkdown-CLI-templppt.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  expportprg_solo: Tx-exportToMarkdown-CLI-templppt.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs
mdhtml:
  expportprg: exportSingle-htmlCLI.ajs
  expportprg_dd: Tx-exportToMarkdown-CLI-md-drivingview.ajs
  # exportSingle-md.ajs | exportSingle-htmlCLI.ajs
  expportprg_rept: exportSingle-htmlCLI.ajs 
