development:
  rutausr: 
  rutamodelo: 
  rutaprg: 
  prg: 
  rutaexpportprg: 
  expportprg: 
deploy:
  origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  destinomd: /Users/hwo/gh/pgn/pgn-078
  origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  gitorigen: /Users/hwo/gh/pgn/pgn-078
publish:
  gitorigen: /Users/hwo/gh/pgn/pgn-078 
mddoc:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/tex-plantll-hv/contd/docx
  rutaCompleta: no
mdtex:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/tex-plantll-hv/contd/tex
  rutaCompleta: no
mdppt:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/tex-plantll-hv/contd/ppt
  rutaCompleta: no
mdhtml:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/archigit/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/tex-plantll-hv/contd/html
  rutaCompleta: no
