development:
  rutausr: 
  rutamodelo: 
  rutaprg: 
  prg: 
  rutaexpportprg: 
  expportprg: 
deploy:
  origenmd: /Users/hwo/Downloads/tmpr/pgnmd
  destinomd: /Users/hwo/gh/pgn/pgn-078
  origenhtml: /Users/hwo/Downloads/tmpr/pgnarchidoc
ccambio:
  gitorigen: /Users/hwo/gh/pgn/pgn-078
publish:
  gitorigen: /Users/hwo/gh/pgn/pgn-078 
mddoc:
  rutausr: $HOME/git
  rutamodelo: $HOME/git/models/modelocontenidos
  rutaprg: $HOME/git/jarchi-hwo/scr
  rutaexpportprg: $HOME/git/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /git/tex-plantll-hv/contd/docx
  rutaCompleta: no
mdtex:
  rutausr: $HOME/gh
  rutamodelo: $HOME/gh/model/modelocontenidos
  rutaprg: $HOME/gh/jarchi-hwo/scr
  rutaexpportprg: $HOME/gh/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /gh/tex-plantll-hv/contd/tex
mdppt:
  rutausr: $HOME/gh
  rutamodelo: $HOME/gh/model/modelocontenidos
  rutaprg: $HOME/gh/jarchi-hwo/scr
  rutaexpportprg: $HOME/gh/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /gh/tex-plantll-hv/contd/ppt
mdhtml:
  rutausr: $HOME/gh
  rutamodelo: $HOME/gh/model/modelocontenidos
  rutaprg: $HOME/gh/jarchi-hwo/scr
  expportprg: exportSingle-htmlCLI.ajs
  rutaMacMD: /gh/tex-plantll-hv/contd/html  
