var ArchiMateObjects=["Resource","Capability", "Value_Stream","Course_Of_Action","Business_Actor","Business_Role", "Business_Collaboration", "Business_Interface", "Business_Process", "Business_Function", "Business_Interaction", "Business_Event", "Business_Service", "Business_Object", "Contract", "Representation", "Product", "Application_Component", "Application_Collaboration", "Application_Interface", "Application_Function", "Application_Interaction", "Application_Process", "Application_Event","Application_Service", "Data_Object", "Node", "Device", "System_Software","Technology_Collaboration", "Technology_Interface", "Path","Communication_Network", "Technology_Function", "Technology_Process", "Technology_Interaction", "Technology_Event", "Technology_Service", "Artifact", "Equipment", "Facility", "Distribution_Network", "Material", "Stakeholder", "Driver", "Assessment", "Goal", "Outcome", "Principle", "Requirement", "Constraint", "Meaning", "Value", "WorkPackage", "Deliverable", "Implementation_Event", "Plateau", "Gap", "Location", "Grouping", "Junction"];

var ArchiMateRelationNames =[ "Access", "Composition", "Flow", "Aggregation", "Assignment", "Influence", "Association", "Realization", "Specialization", "Triggering", "Serving"];
var ArchiMateRelationIDs= [ "a","c","f","g","i","n","o","r","s","t","v"];
var ja_ArchiMateViewpoints=["application_cooperation", "application_usage",
"business_process_cooperation","capability","goal_realization","implementation_deployment","implementation_migration",
"information_structure","layered","migration","motivation","organization","outcome_realization","physical","product",
"project","requirements_realization","resource","service_realization","stakeholder","strategy","technology","technology_usage"];
   
var  ArchiMateRelations=
        [
         [ "Resource",
          "cfgostv", "fiotv", "fiotv","forv",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cfginorstv","finortv" ],
         [ "Capability",
          "fotv", "cfgostv","fotv","fortv",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cfgnorstv","fnortv" ],
          [ "Value_Stream",
          "fotv", "fotv", "cfgostv","fortv",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cfgnorstv","fnortv" ],
         [ "Course_Of_Action",
          "fotv", "fotv", "fotv","cfgostv",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cfgnorstv","fnortv" ],
         [ "Business_Actor",
          "or", "or", "or","or",
          "cfgostv","fiotv","fotv","cfgiotv","fiotv","fiotv","fiotv","fiotv","fiortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "ino","no","no","nor","nor","nor","nor","nor","no","no",
          "io","o","io","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Business_Role",
          "or", "or", "or","or",
          "fotv","cfgostv","fotv","cfgotv","fiotv","fiotv","fiotv","fiotv","fiortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "ino","no","no","nor","nor","nor","nor","nor","no","no",
          "io","o","io","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Business_Collaboration",
          "or", "or", "or","or",
          "fgotv","fgiotv","cfgostv","cfgiotv","fiotv","fiotv","fiotv","fiotv","fiortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "ino","no","no","nor","nor","nor","nor","nor","no","no",
          "io","o","io","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Business_Interface",
          "or", "or", "or","or",
          "fotv","fotv","fotv","cfgostv","fotv","fotv","fotv","fotv","fiotv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fot","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fot","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Business_Process",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","cfgostv","cfgotv","cfgotv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Business_Function",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","cfgotv","cfgostv","cfgotv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Business_Interaction",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","cfgotv","cfgotv","cfgostv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],       
         [ "Business_Event",
          "o", "o", "o","o",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","fotv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
          [ "Business_Service",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fot","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],  
         [ "Business_Object",
          "or", "or", "or","or",
          "o","o","o","o","o","o","o","o","o","cgos","cgos","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor"],
         [ "Contract",
          "or", "or", "or","or",
          "o","o","o","o","o","o","o","o","o","cgos","cgos","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Representation",
          "or", "or", "or","or",
          "o","o","o","o","o","o","o","o","o","or","or","cgos","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Product",
          "or", "or", "or","or",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","cfgortv","acgo","acgo","acgo","cfgostv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","cfgortv","acgo",
          "fortv","fortv","fortv","fotv","fortv","fotv","fotv","fortv","fortv","fortv","fortv","cfgortv","acgo","fortv","fortv","fotv","acgo",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Application_Component",
          "or", "or", "or","or",
          "fotv","fotv","fotv","fortv","fortv","fortv","fortv","fortv","fortv","ao","ao","ao","fotv",
          "cfgorstv","fotv","cfgortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Application_Collaboration",
          "or", "or", "or","or",
          "fotv","fotv","fotv","fortv","fortv","fortv","fortv","fortv","fortv","ao","ao","ao","fotv",
          "fgortv","cfgorstv","cfgortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Application_Interface",
          "or", "or", "or","or",
          "fotv","fotv","fotv","fortv","fotv","fotv","fotv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","cfgostv","fotv","fotv","fotv","fotv","fiotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Application_Function",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","cfgostv","cfgotv","cfgotv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Application_Interaction",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","cfgotv","cfgostv","cfgotv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Application_Process",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","cfgotv","cfgotv","cfgostv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Application_Event",
          "o", "o", "o","o",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","ao","o","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Application_Service",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Data_Object",
          "or", "or", "or","or",
          "o","o","o","o","o","o","o","o","o","or","or","o","o",
          "o","o","o","o","o","o","o","o","cgos",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Node",
          "or", "or", "or","or",
          "fiortv","fiortv","fiotv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "cfgiorstv","cfgiorstv","cfgiorstv","fotv","cfgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","cfgiorstv","cfgiorstv","fotv","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Device",
          "or", "or", "or","or",
          "fiortv","fiortv","fiotv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "cfgiorstv","cfgiorstv","cfgiorstv","fotv","cfgiortv","fot","fot","fiortv","fiortv","fiortv","fiortv","fiortv","aio","cfgiorstv","cfgiorstv","fotv","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "System_Software",
          "or", "or", "or","or",
          "fiortv","fiortv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "cfgiorstv","cfgiorstv","cfgiorstv","fotv","cfgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","cfgiorstv","cfgiorstv","fotv","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Technology_Collaboration",
          "or", "or", "or","or",
          "fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "fgiortv","fgiortv","fgiortv","cfgostv","cfgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","fgiortv","fgiortv","fotv","aio",
           "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
["Technology_Interface",
          "or", "or", "or","or",
          "fotv","fotv","fotv","fortv","fotv","fotv","fotv","fotv","fotv","ao","ao","ao","fotv",
          "fotv","fotv","fortv","fotv","fotv","fotv","fotv","fotv","ao",
          "fotv","fotv","fotv","fotv","cfgostv","fotv","fotv","fotv","fotv","fotv","fotv","fiotv","ao","fotv","fotv","fotv","ao",
           "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
["Path",
          "or", "or", "or","or",
          "fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "fgiortv","fgiortv","fgiortv","fgotv","fgiortv","cfgostv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","fgiortv","fgiortv","fotv","aio",
           "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
["Communication_Network",
          "or", "or", "or","or",
          "fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "fgiortv","fgiortv","fgiortv","fortv","fgiortv","fortv","cfgostv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","fgiortv","fgiortv","fotv","aio",
           "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
["Technology_Function",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","cfgotv","cfgotv","fotv","fortv","ao","fotv","fotv","fotv","ao",
           "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],          
        [ "Technology_Process",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fo",
          "fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgotv","cfgostv","cfgotv","fotv","fortv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Technology_Interaction",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fortv","fortv","fortv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgotv","cfgotv","cfgostv","fotv","fortv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorstv","afnortv" ],
         [ "Technology_Event",
          "o", "o", "o","o",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fortv","fotv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fortv","fotv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgost","fotv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgnorst","afnort" ],
         [ "Technology_Service",
          "o", "or", "or","or",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fortv","ao","ao","ao","fotv",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fortv","ao",
          "fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","fotv","cfgostv","ao","fotv","fotv","fotv","ao",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfgorstv","afnortv" ],
         [ "Artifact",
          "or", "or", "or","or",
          "or","or","or","or","or","or","or","or","or","or","or","o","o",
          "or","or","or","or","or","or","or","or","or",
          "or","or","or","o","or","o","o","or","or","or","or","or","cgos","or","or","or","o",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnosr","nor" ],
         ["Equipment",
          "or", "or", "or","or",
          "fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "cfgiorstv","cfgiorstv","cfgiorstv","fotv","cfgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","cfgiorstv","cfgiorstv","fotv","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginostv","afinortv" ],
         [ "Facility",
          "or", "or", "or","or",
          "fiortv","fiortv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "cfgiorstv","cfgiorstv","cfgiorstv","fotv","cfgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","cfgiorstv","cfgiorstv","fotv","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginostv","afinortv" ],
         [ "Distribution_Network",
          "or", "or", "or","or",
          "fiortv","fiortv","fiotv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","ao","ao","ao","fotv",
          "fortv","fortv","fortv","fortv","fortv","fortv","fortv","fortv","ao",
          "fgiortv","fgiortv","fgiortv","fortv","fgiortv","fotv","fotv","fiortv","fiortv","fiortv","fiortv","fiortv","aio","fgiortv","fgiortv","cfgost","aio",
          "nor","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","fotv",
          "acfginorstv","afinortv" ],
         [ "Material",
          "or", "or", "or","or",
          "o","o","o","o","o","o","o","o","o","or","or","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","cgos",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Stakeholder",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "cgnos","no","no","no","no","no","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "Driver",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","cgnos","no","no","no","no","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "Assessment",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","cgnos","no","no","no","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "Goal",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","cgnos","no","no","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "Outcome",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","cgnos","no","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Principle",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","cgnos","no","no","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Requirement",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","cgnos","cgnos","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Constraint",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","nor","nor","nor","cgnos","cgnos","no","no",
          "o","o","o","o","o","o",
          "cgnors","nor" ],
         [ "Meaning",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","no","no","no","no","no","cgnos","no",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "Value",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","no","no","no","no","no","no","cgnos",
          "o","o","o","o","o","o",
          "cgnos","no" ],
         [ "WorkPackage",
          "or", "or", "or","or",
          "or","or","or","or","or","or","or","or","or","or","or","or","or",
          "or","or","or","or","or","or","or","or","or",
          "or","or","or","or","or","or","or","or","or","or","or","or","or","or","or","or","or",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "cfgost","aor","fot","fort","o","or",
          "acfgnorst","afnort" ],
         [ "Deliverable",
          "or", "or", "or","or",
          "or","or","or","or","or","or","or","or","or","or","or","or","or",
          "or","or","or","or","or","or","or","or","or",
          "or","or","or","or","or","or","or","or","or","or","or","or","or","or","or","or","or",
          "no","no","no","nor","nor","nor","nor","nor","no","no",
          "o","cgos","o","or","o","or",
          "cgnors","nor" ],
         [ "Implementation_Event",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "no","no","no","no","no","no","no","no","no","no",
          "fot","ao","cfgost","fot","o","o",
          "acfgnost","afnot" ],
         [ "Plateau",
          "cgor", "cgor", "cgor","cgor",
          "cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor",
          "cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor",
          "cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor","cgor",
          "no","no","no","cgnor","nor","nor","cgnor","cgnor","no","no",
          "fot","ao","fot","cfgost","o","cgor",
          "acfgnorst","acfgnort" ],
         [ "Gap",
          "o", "o", "o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","o","o","o","o","o","o",
          "o","o","o","o","cgos","o",
          "cgos","o" ],
         [ "Location",
          "cgor", "cgor", "cgor","cgor",
          "cfgiortv","cfgiortv","cfgiotv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","acgo","acgo","acgo","cfgotv",
          "cfgotv","cfgortv","cfgortv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","acgo",
          "cfgiortv","cfgiortv","cfgiortv","cfgortv","cfgiortv","cfgortv","cfgotv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","cfgiortv","acgio","cfgiortv","cfgiortv","cfgotv","acgio",
          "cgnor","cgno","cgno","cgnor","cgnor","cgnor","cgnor","cgnor","cgno","cgno",
          "cgo","cgo","cgo","cgo","cgo","cfgostv",
          "acfginorstv","acfginortv" ] ,
         [ "Grouping",
          "cfgorstv", "cfgiorstv", "cfgiorstv","cfgorstv",

          "cfgiorstv","cfgiortsv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","acgors","acgors","acgors","cfgorstv",

          "cfgorstv","cfgorstv","cfgorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","acgors",

          "cfgiorstv","cfgiorstv","cfgiorstv","cfgorstv","cfgiorstv","cfgorstv","cfgorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","cfgiorstv","acgiors","cfgiorstv","cfgiorstv","cfgorstv","acgiors",
          "cginors","cgnos","cgnos","cgnors","cgnors","cgnors","cgnors","cgnors","cgnos","cgnos",

          "cfgiost","acgors","cfgiost","cfgorst","cgos","cfgorstv",
          "acfginorstv","acfginortv" ],
         [ "Junction",
          "fortv", "fiortv","fiortv","fortv",
          "fiortv","fiortv","fortv","fiortv","fiortv","fiortv","fiortv","fiortv","fiortv","aor","aor","aor","fortv",

          "fortv","fortv","fortv","fiortv","fiortv","fiortv","fiortv","fiortv","aor",

          "fiortv","fiortv","fiortv","fortv","fiortv","fortv","fortf","fiortv","fiortv","fiortv","fiortv","fiortv","aior","fiortv","fiortv","fortv","aior",

          "inor","no","no","nor","nor","nor","nor","nor","no","no",
          "fiot","aor","fiot","fort","o","fortv",
          "afinortv","afinortv" ]
         ];

/*
 * Created from the jArchi documentation
 * It should be considered that it is Archi similar except for this point:
 * - No caps and minus are used for jArchi while Caps and underscores are used 
 *   for the ArchiMate relationships matrix 
 */

var ja_ArchiMateObjects=["resource","capability","value-stream","course-of-action","business-actor","business-role", "business-collaboration", "business-interface", "business-process", "business-function", "business-interaction", "business-event", "business-service", "business-object", "contract", "representation", "product", "application-component", "application-collaboration", "application-interface", "application-function", "application-interaction", "application-process", "application-event","application-service", "data-object", "node", "device", "system-software","technology-collaboration", "technology-interface", "path","communication-network", "technology-function", "technology-process", "technology-interaction", "technology-event", "technology-service", "artifact", "equipment", "facility", "distribution-network", "material", "stakeholder", "driver", "assessment", "goal", "outcome", "principle", "requirement", "constraint", "meaning", "value", "work-package", "deliverable", "implementation-event", "plateau", "gap", "location", "grouping", "junction"];

/*
 * Created from archimate3_Model.xsd
 * It should be considered that it is Archi similar except for these points:
 * - Caps used but neither underscores nor minus
 * - AndJunction and OrJunction are distinguished, Junction is generic
 */
var oef_ArchiMateObjects=["Resource","Capability","ValueStream", "CourseOfAction","BusinessActor","BusinessRole", "BusinessCollaboration", "BusinessInterface", "BusinessProcess", "BusinessFunction", "BusinessInteraction", "BusinessEvent", "BusinessService", "BusinessObject", "Contract", "Representation", "Product", "ApplicationComponent", "ApplicationCollaboration", "ApplicationInterface", "ApplicationFunction", "ApplicationInteraction", "ApplicationProcess", "ApplicationEvent","ApplicationService", "DataObject", "Node", "Device", "SystemSoftware","TechnologyCollaboration", "TechnologyInterface", "Path","CommunicationNetwork", "TechnologyFunction", "TechnologyProcess", "TechnologyInteraction", "TechnologyEvent", "TechnologyService", "Artifact", "Equipment", "Facility", "DistributionNetwork", "Material", "Stakeholder", "Driver", "Assessment", "Goal", "Outcome", "Principle", "Requirement", "Constraint", "Meaning", "Value", "WorkPackage", "Deliverable", "ImplementationEvent", "Plateau", "Gap", "Location", "Grouping", "Junction"];

/*
 * Created from https://github.com/ebbypeter/Archimate-PlantUML/blob/master/Archimate.puml
 * It should be considered that ArchiMate-PlantUML considers:
 * - Business_Location elements which are not part of the ArchiMate specification
 * - Junction_Or and Junction_And for Junction with is generic
 * - Group which is considered like the other model elements, 
 *   but is a visual element in ArchiMate
 * This array is created from the ArchiMateObjects.
 * It constitutes a mapping to Archimate-PlantUML (except for Junction) and 
 */
var puml_ArchiMateObjects=["Strategy_Resource","Strategy_Capability", "Value_Stream","Strategy_CourseOfAction","Business_Actor","Business_Role", "Business_Collaboration", "Business_Interface", "Business_Process", "Business_Function", "Business_Interaction", "Business_Event", "Business_Service", "Business_Object", "Business_Contract", "Business_Representation", "Business_Product", "Application_Component", "Application_Collaboration", "Application_Interface", "Application_Function", "Application_Interaction", "Application_Process", "Application_Event","Application_Service", "Application_DataObject", "Technology_Node", "Technology_Device", "Technology_SystemSoftware","Technology_Collaboration", "Technology_Interface", "Technology_Path","Technology_CommunicationNetwork", "Technology_Function", "Technology_Process", "Technology_Interaction", "Technology_Event", "Technology_Service", "Technology_Artifact", "Physical_Equipment", "Physical_Facility", "Physical_DistributionNetwork", "Physical_Material", "Motivation_Stakeholder", "Motivation_Driver", "Motivation_Assessment", "Motivation_Goal", "Motivation_Outcome", "Motivation_Principle", "Motivation_Requirement", "Motivation_Constraint", "Motivation_Meaning", "Motivation_Value", "Implementation_WorkPackage", "Implementation_Deliverable", "Implementation_Event", "Implementation_Plateau", "Implementation_Gap", "Other_Location", "Grouping", "Junction_Or"];

/*
 * A particular attention is to be paid when dealing with:
 * - junctions, due to the fact and_junction and or_junction are not distinquished
 *   in the ArchiMate Relationships matrix
 * - ArchiMate elements naming conventions are not the same for the relationship matrix, 
 *   Archi, jArchi, Open Exchange Format or ArchiMate-PlantUML
 * - ArchiMate-PlantUML distinguishes Business_Location and Other_Location, the first one 
 *   doesn't exist in the specification.
 */